dist: focal

language: minimal

before_install: 
  - sudo add-apt-repository ppa:neovim-ppa/stable 
  - sudo apt-get update
  - sudo apt-get -y install neovim

install:
  - git clone https://github.com/leafOfTree/vim-vue-plugin ../vim-vue-plugin --depth=1
  - git clone https://github.com/leafOfTree/vim-svelte-plugin ../vim-svelte-plugin --depth=1

  - git clone https://github.com/digitaltoad/vim-pug ../vim-pug --depth=1
  - git clone https://github.com/kchmck/vim-coffee-script ../vim-coffee-script --depth=1
  - git clone https://github.com/leafgarland/typescript-vim ../typescript-vim --depth=1
  - git clone https://github.com/iloginow/vim-stylus.git ../vim-stylus --depth=1

script:
  - bash ./start.sh vue vim-vue-plugin
  - bash ./start.sh svelte vim-svelte-plugin
